src/Entity/Representation.php
<?php

namespace App\Entity;

use App\Repository\RepresentationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RepresentationRepository::class)
 * @ORM\Table(name="representations")
 */
class Representation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Show::class, inversedBy="representations")
     * @ORM\JoinColumn(nullable=false, name="show_id", referencedColumnName="id")
     */
    private $the_show;

    /**
     * @ORM\Column(type="datetime")
     */
    private $schedule;

    /**
     * @ORM\ManyToOne(targetEntity=Location::class, inversedBy="representations")
     * @ORM\JoinColumn(name="location_id", referencedColumnName="id")
     */
    private $the_location;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="representation", orphanRemoval=true)
     */
    private $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTheShow(): ?Show
    {
        return $this->the_show;
    }

    public function setTheShow(?Show $the_show): self 
    {
        $this->the_show = $the_show;

        return $this;
    }

    public function getSchedule(): ?\DateTimeInterface
    {
        return $this->schedule;
    }

    public function setSchedule(\DateTimeInterface $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getTheLocation(): ?Location
    {
        return $this->the_location;
    }

    public function setTheLocation(?Location $the_location): self
    {
        $this->the_location = $the_location;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setRepresentation($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->contains($reservation)) {
            $this->reservations->removeElement($reservation);
            // set the owning side to null (unless already changed)
            if ($reservation->getRepresentation() === $this) {
                $reservation->setRepresentation(null);
            }
        }

        return $this;
    }
}

src/Controller/RepresentationController.php
<?php

namespace App\Controller;

use App\Repository\RepresentationRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class RepresentationController extends AbstractController
{
    /**
     * @Route("/representation", name="representation")
     */
    public function index(RepresentationRepository $repo)
    {
        $representations = $repo->findAll();

        return $this->render('representation/index.html.twig', [
            'representations' =>  $representations,
        ]);
    }

    /**
     * @Route("/representation/{id}", name="show_representation")
     */
    public function show($id, RepresentationRepository $repo)
    {
        $representation = $repo->find($id);

        return $this->render('representation/show.html.twig', [
            'representation' => $representation,
        ]);

    }
    
}

templates/representation/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title %}Hello RepresentationController!{% endblock %}

{% block body %}
    <h1>Liste des Représentations</h1>
    <ul>
    {% for representation in representations %}
        <li> {{ representation.theShow.title }}
            {% if representation.theLocation %} 
            - <span> {{ representation.theLocation.designation }} </span>
            {% endif %}
            - <datetime> {{ representation.schedule|date('d-m-Y H:i') }} </datetime>
        </li>
    {% endfor %}
    </ul>
    
{% endblock %}

templates/representation/show.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title %} Fiche d'une représentation {% endblock %}

{% block body %}

    <pre>
        {{ dump(representation.theLocation) }}
    </pre>
    <article>
        <h1>Représentation du {{representation.schedule|date('d-m-Y H:i')}} à 
        {{ representation.schedule|date('G:i')}}
        </h1>
        <p><strong>Spectacle: </strong>{{ representation.theShow.title }}</p>
        <p><strong>Lieu:</strong>
        {% if representation.theLocation %}
        {{ representation.theLocation.designation }}
        {% elseif representation.theShow.location %}
        {{ representation.theShow.theLocation.designation }}
        {% else %}
        <em>A déterminer</em>
        {% endif %}
        </p>
    </article>

{% endblock %}